spring:
  application:
    name: rest-with-spring-boot-and-java-erudio

  datasource:
    url: jdbc:mysql://localhost:3306/erudio?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
